NAME	= philosophers

CC		= cc
CFLAGS	= -Wall -Wextra -Werror -g

SRCS	= src/*.c
OBJS	= $(SRCS:.c=.o)

INC		= -Iinclude

all: $(NAME)

$(NAME): $(OBJS)
	$(CC) $(CFLAGS) $(OBJS) $(INC) -o $(NAME)

%.o: %.c
	$(CC) $(CFLAGS) $(INC) -c $< -o $@

clean:
	rm -f $(OBJS)

fclean: clean
	rm -f $(NAME)

re: fclean all

v: re
	clear
	valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes -s --track-fds=yes ./$(NAME)

.PHONY: all clean fclean re v